tradeValidation:
    validatorsForTradeType:
        ALL: 
            - ValueDateNotBeforeTradeDateValidator
            - ValueDateOnWorkingDayValidator
            - CounterPartyValidator
            - CurrencyValidator
        Spot: 
            - SpotValueDateValidator
        Forward:
            - ForwardValueDateValidator
        VanillaOption:
            - OptionStyleValidator
            - OptionExcerciseStartDateValidator
            - OptionExpiryDateAndPremiumDateValidator