tradeValidation:
    validatorsForTradeType:
        ALL: 
            - ValueDateNotBeforeTradeDateValidator
            - ValueDateNotOnNonWorkingDayForCurrencValidator
            - CounterPartyValidator
            - CurrencyValidator
        Spot: 
            - ValueDateAgainstProductTypeValidator
        Forward:
            - ValueDateAgainstProductTypeValidator
        VanillaOption:
            - OptionStyleValidator
            - OptionExcerciseDateValidator
            - OptionExpiryDateAndPremiumDateValidator