tradeValidation:
    validatorsForTradeType:
        ALL: 
            - ValueDateNotBeforeTradeDateValidator
            - ValueDateNotOnNonWorkingDayForCurrencValidator
            - CounterPartyValidator
            - CurrencyValidator
        SPOT: 
            - ValueDateAgainstProductTypeValidator
        FORWARD:
            - ValueDateAgainstProductTypeValidator
        OPTION:
            - OptionStyleValidator
            - OptionExcerciseDateValidator
            - OptionExpiryDateAndPremiumDateValidator